# file: postgresql/tasks/databases.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: PostgreSQL | Make sure the PostgreSQL databases are present
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner | default(postgresql_database_owner) }}"
    encoding: "{{ item.encoding | default(postgresql_encoding) }}"
#    lc_collate: "{{ item.lc_collate | default(postgresql_locale) }}" # Changing LC_COLLATE is not supported. Current LC_COLLATE: C.UTF-8
    lc_ctype: "{{ item.lc_ctype | default(postgresql_ctype) }}"
    port: "{{ postgresql_port }}"
    template: "template0"
    state: present
    login_user: "{{ postgresql_admin_user }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_databases }}"
  when: postgresql_databases|length > 0

- name: PostgreSQL | Add extensions to the databases
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  postgresql_ext:
    db: "{{ item.0.db }}"
    login_user: "{{ postgresql_service_user }}"
    port: "{{ postgresql_port }}"
    name: "{{ item.1 }}"
  with_subelements:
    - "{{ postgresql_database_extensions }}"
    - extensions
  register: result

#
# Add following extensions: pgstattupl, pg_stat_statements, plpythonu, pg_buffercache, pg_prewarm, pageinspect
# ALTER SYSTEM SET shared_preload_libraries = 'pg_prewarm';
#
- name: PostgreSQL | Add pg_prewarm to the databases with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS pg_prewarm;'"
  with_items: "{{ postgresql_databases }}"
  register: pg_prewarm_ext_result
  failed_when: pg_prewarm_ext_result.rc != 0 and ("already exists, skipping" not in pg_prewarm_ext_result.stderr)
  changed_when: pg_prewarm_ext_result.rc == 0 and ("already exists, skipping" not in pg_prewarm_ext_result.stderr)
  when: item.pg_prewarm is defined and item.pg_prewarm

- name: PostgreSQL | Add pg_stat_statements to the databases with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS pg_stat_statements;'"
  with_items: "{{ postgresql_databases }}"
  register: pg_stat_statements_ext_result
  failed_when: pg_stat_statements_ext_result.rc != 0 and ("already exists, skipping" not in pg_stat_statements_ext_result.stderr)
  changed_when: pg_stat_statements_ext_result.rc == 0 and ("already exists, skipping" not in pg_stat_statements_ext_result.stderr)
  when: item.pg_stat_statements is defined and item.pg_stat_statements

- name: PostgreSQL | Add pgstattuple to the databases with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS pgstattuple;'"
  with_items: "{{ postgresql_databases }}"
  register: pgstattuple_ext_result
  failed_when: pgstattuple_ext_result.rc != 0 and ("already exists, skipping" not in pgstattuple_ext_result.stderr)
  changed_when: pgstattuple_ext_result.rc == 0 and ("already exists, skipping" not in pgstattuple_ext_result.stderr)
  when: item.pgstattuple is defined and item.pgstattuple

- name: PostgreSQL | Add hstore to the databases with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS hstore;'"
  with_items: "{{ postgresql_databases }}"
  register: hstore_ext_result
  failed_when: hstore_ext_result.rc != 0 and ("already exists, skipping" not in hstore_ext_result.stderr)
  changed_when: hstore_ext_result.rc == 0 and ("already exists, skipping" not in hstore_ext_result.stderr)
  when: item.hstore is defined and item.hstore

- name: PostgreSQL | Add uuid-ossp to the database with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";'"
  with_items: "{{ postgresql_databases }}"
  register: uuid_ext_result
  failed_when: uuid_ext_result.rc != 0 and ("already exists, skipping" not in uuid_ext_result.stderr)
  changed_when: uuid_ext_result.rc == 0 and ("already exists, skipping" not in uuid_ext_result.stderr)
  when: item.uuid_ossp is defined and item.uuid_ossp

- name: PostgreSQL | Add postgis to the databases with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS postgis;'&&psql {{ item.name }} -c 'CREATE EXTENSION IF NOT EXISTS postgis_topology;'"
  with_items: "{{ postgresql_databases }}"
  when: item.gis is defined and item.gis

- name: PostgreSQL | add cube to the database with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION if not exists cube;'"
  with_items: "{{ postgresql_databases }}"
  when: item.cube is defined and item.cube

- name: PostgreSQL | Add plpgsql to the database with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS plpgsql;'"
  with_items: "{{ postgresql_databases }}"
  when: item.plpgsql is defined and item.plpgsql

- name: PostgreSQL | add earthdistance to the database with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION if not exists earthdistance;'"
  with_items: "{{ postgresql_databases }}"
  when: item.earthdistance is defined and item.earthdistance

- name: PostgreSQL | Add citext to the database with the requirement
  become: yes
  become_user: "{{ postgresql_service_user }}"
  shell: "{{ postgresql_bin_directory }}/psql {{ item.name }} --username {{ postgresql_admin_user }} -p {{ postgresql_port }} -c 'CREATE EXTENSION IF NOT EXISTS citext;'"
  with_items: "{{ postgresql_databases }}"
  register: citext_ext_result
  failed_when: citext_ext_result.rc != 0 and ("already exists, skipping" not in citext_ext_result.stderr)
  changed_when: citext_ext_result.rc == 0 and ("already exists, skipping" not in citext_ext_result.stderr)
  when: item.citext is defined and item.citext
