# file: postgresql/tasks/extensions/postgis.yml

- name: Include corresponding vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution_release }}  .yml"
    - "../vars/empty.yml"

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | Debian
  apt:
    name: "{{ postgresql_ext_postgis_deps }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_os_family == "Debian"
  notify:
    - restart postgresql
