- name: ensure monit is running
  service:
    name: monit
    state: started

# template a config file
- name: (Monit) copy the pgbouncer monit service file
  template:
    src: etc_monit_conf.d_pgbouncer.j2
    dest: /etc/monit/conf.d/pgbouncer
  notify: restart monit

# we need to restart before monit is called
- meta: flush_handlers

# Manage the state of program "pgbouncer" to be in "started" state.
- monit:
    name: pgbouncer
    state: started
  ignore_errors: true



